  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    env: metrics
spec:
  selector:
    matchLabels:
      env: metrics
  template:
    metadata:
      name: prometheus
      labels:
        env: metrics
    spec:
      containers:
      - image: prom/prometheus
        name: prom
        args:
        - '--config.file=/prometheus.yml'
        - --storage.tsdb.path='prometheus_data/
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus_persistent_storage
          mountPath: prometheus_data/
        - name: prometheus_script
          mountPath: /prometheus.yml
          subPath: prometheus.yml  
      volumes:
      - name: prometheus_persistent_storage
        persistentVolumeClaim:
          claimName: prometheus_storage_pvc
      - name: prometheus_script
        configMap:
          name: prometheus_config