apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus_storage_pvc
  labels:
    vol: prometheus_storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
