kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana_config
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: server
        url: http://192.168.42.111:30001
        version: 1
        editable: true